import subprocess
import os
from datetime import datetime

REPORT_FILE = "log_analysis_report.txt"
CLASH_REPORT_FILE = "clash_report.txt"  # The file generated by your first script

CRITICAL_KEYWORDS = [
    "error", "fail", "failed", "critical",
    "panic", "exception", "fatal", "segfault"
]

def get_running_containers():
    result = subprocess.run(
        ["docker", "ps", "--format", "{{.Names}}"],
        capture_output=True, text=True
    )
    containers = result.stdout.strip().split("\n")
    return [c for c in containers if c]

def get_container_image(container):
    result = subprocess.run(
        ["docker", "inspect", "--format", "{{.Config.Image}}", container],
        capture_output=True, text=True
    )
    return result.stdout.strip()

def get_container_logs(container):
    result = subprocess.run(
        ["docker", "logs", "--tail", "300", container],
        capture_output=True, text=True, errors="ignore"
    )
    return result.stdout

def analyze_logs(log_text):
    lines = log_text.split("\n")
    critical = []
    for line in lines:
        lower = line.lower()
        if any(word in lower for word in CRITICAL_KEYWORDS):
            critical.append(line)
    return critical

# ---------- NEW FUNCTION: Process Clash Report ----------
def analyze_clash_report():
    """Reads the clash_report.txt and filters for specific events."""
    clash_summary = []
    
    if not os.path.exists(CLASH_REPORT_FILE):
        return ["No clash report file found (Script 1 might not have run yet)."]

    try:
        with open(CLASH_REPORT_FILE, "r", encoding="utf-8") as f:
            lines = f.readlines()
            
        for line in lines:
            line = line.strip()
            # We filter for specific tags used in your first script
            if "[WARNING]" in line or "[RECOVERY]" in line or "[CRITICAL]" in line:
                clash_summary.append("⚠️ " + line)
            elif "[SUCCESS]" in line:
                clash_summary.append("✅ " + line)
                
    except Exception as e:
        return [f"Error reading clash report: {str(e)}"]

    return clash_summary

# ---------- Main Controller ----------
def main():
    report = []
    timestamp = datetime.now()

    report.append("==============================================")
    report.append("        DOCKER SYSTEM DIAGNOSTIC REPORT       ")
    report.append("==============================================")
    report.append(f"Report Generated At : {timestamp}")
    report.append("Objective :")
    report.append("1. Analyze Port Clashes & Infrastructure Issues (from clash_report.txt)")
    report.append("2. Analyze Application Logs for Crashes/Errors")
    report.append("\n--------------------------------------------------\n")

    # =======================================================
    # SECTION 1: INFRASTRUCTURE & PORT HEALTH (Added Feature)
    # =======================================================
    report.append(">>> SECTION 1: INFRASTRUCTURE & PORT HEALTH CHECK")
    
    clash_events = analyze_clash_report()
    
    if not clash_events:
        report.append("Status : STABLE")
        report.append("Details: No port clashes or critical infrastructure issues recorded.")
    else:
        report.append(f"Status : ATTENTION REQUIRED ({len(clash_events)} Events)")
        report.append("Details: The following port/container incidents were detected:")
        for event in clash_events:
            report.append("  " + event)
            
    report.append("\n--------------------------------------------------\n")

    # =======================================================
    # SECTION 2: APPLICATION LOG ANALYSIS
    # =======================================================
    report.append(">>> SECTION 2: APPLICATION LOG ANALYSIS")
    
    containers = get_running_containers()

    if not containers:
        report.append("No running containers detected for log analysis.")
    else:
        report.append(f"Total Running Containers Detected : {len(containers)}")
        report.append("Starting log inspection for each container...\n")

        for c in containers:
            image = get_container_image(c)
            logs = get_container_logs(c)
            critical_entries = analyze_logs(logs)

            report.append("--------------------------------------------------")
            report.append(f"Container Name : {c}")
            report.append(f"Container Image: {image}")
            report.append("Log Scope      : Last 300 log lines analyzed")
            report.append("Analysis Result:")

            if not critical_entries:
                report.append("Status : HEALTHY ✅")
                report.append("Details: No critical or error-level log entries detected.")
            else:
                report.append("Status : ATTENTION REQUIRED ⚠️")
                report.append(f"Details: {len(critical_entries)} critical/error-level entries detected.")
                report.append("Sample Critical Entries:")
                for entry in critical_entries[:5]:
                    report.append("  → " + entry[:100] + "...") # Truncate long lines
                report.append("Inference: Presence of error keywords indicates potential service instability.")

            report.append("--------------------------------------------------\n")

    report.append("FINAL SUMMARY")
    report.append("Diagnostic complete. Please review any [WARNING] items in Section 1")
    report.append("and any 'ATTENTION REQUIRED' items in Section 2.")
    report.append("\n===== END OF LOG ANALYSIS REPORT =====")

    # Save to file
    with open(REPORT_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(report))

    print("\n".join(report))
    print(f"\n[✓] Detailed consolidated report saved as: {REPORT_FILE}")

if __name__ == "__main__":
    main()