version: "3.8"

services:
  web:
    image: nginx:latest
    container_name: test_nginx
    volumes:
      - test_volume:/usr/share/nginx/html
    ports:
      - "8080:80"

volumes:
  test_volume:
