version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - nutrient-tracker-network

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:example@db:5432/nutrient_tracker_development
    networks:
      - nutrient-tracker-network

networks:
  nutrient-tracker-network:
    driver: bridge

volumes:
  db_data:
