FROM python:3.11-slim

WORKDIR /app

# System libs needed for psycopg2 + tailwind
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# collect static assets for Django
RUN python manage.py collectstatic --noinput

ENV PORT=8000

EXPOSE 8000

CMD ["gunicorn", "STAC.wsgi:application", "-b", "0.0.0.0:8000"]


