version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    networks:
      - app_network
    ports:
      - "80:80"  # Expose frontend service to the outside world on port 80
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    networks:
      - app_network
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    depends_on:
      - db
    ports:
      - "5000:5000"  # Expose backend service to the outside world on port 5000

  db:
    image: postgres:13
    networks:
      - app_network
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=mydatabase
    expose:
      - "5432"  # Expose only to the backend service, not externally
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  app_network:
    driver: bridge  # This isolates the backend and database from the outside world

volumes:
  db_data:
