version: '3.9'

services:
  nutrient-tracker:
    build:
      context: ./Nutrient-Tracker
    ports:
      - "8080:3000"
    networks:
      - app-network
    depends_on:
      - db

  tip:
    build:
      context: ./TIP
    ports:
      - "8081:3000"
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nutrient_tracker_development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge